Make it easier to monitor for regressions by running daily
wp-cli/.github pull request #44
Opened 2022-12-16 15:39 UTC by danielbachhuber

Updates the `.github/workflows/testing.yml` file to run tests daily. The workflow badges on https://wp-cli.org/dashboard/ are varying degrees of out of date.

2022-12-16 15:51 UTC, schlessera commented
Note: Cron jobs are automatically deactivated for repos that don't get changes for a certain  number of days (I think it is 90 days), so we'll have to monitor the monitoring! :)

2022-12-16 15:53 UTC, schlessera commented
Hmm, proper etiquette would suggest we have different times for different repos, to not start a full cascade at midnight and overload systems. However, that is then not easy to keep in sync anymore. Maybe we can have differing cron jobs in a separate file that is not being synced and just references the other one to execute?

2022-12-16 15:53 UTC, schlessera requested changes
All at the same time is not nice towards the GitHub DevOps team.

2022-12-16 16:13 UTC, danielbachhuber commented
> Maybe we can have differing cron jobs in a separate file that is not being synced and just references the other one to execute?

@schlessera I suppose we could.

> Hmm, proper etiquette would suggest we have different times for different repos, to not start a full cascade at midnight and overload systems.
>
> [...]
>
> All at the same time is not nice towards the GitHub DevOps team.

I appreciate the concern 😊 I imagine GitHub Actions handles many (tens?) thousands of jobs/minute and have some fancy auto-scaling infrastructure. These jobs are probably a small drop in a very large ocean.

We could change it to a different hour and minute of the day? I think I'd prefer to not add complexity where it's probably not warranted.

2023-01-03 14:48 UTC, schlessera approved these changes

2023-01-03 14:49 UTC, schlessera commented
Ok, let's just see if we experience slowdowns.

2023-01-03 14:49 UTC, merged

2023-01-05 19:42 UTC, danielbachhuber commented
@ocean90 Thanks for the suggestion! Doing with https://github.com/wp-cli/.github/pull/47